stages:
  - noop
  - build

noop:
    stage: noop
    script:
        - echo "This is a no-op job"

include:
  - component: $CI_SERVER_FQDN/shared/blueprints/docker-build@v1.1.1
    rules:
      - if: '$CI_COMMIT_TAG'
    inputs:
      platform: "linux/amd64"
      dockerHubUser: ${DOCKER_HUB_USER}
      dockerHubPat: ${DOCKER_HUB_PAT}
      stage: build
      repo: siteworxpro/top-wallpaper
      tag: "${CI_COMMIT_TAG}"
